# Generated by Django 5.0.7 on 2024-07-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Укажите награду за выполнение привычки",
                max_length=200,
                null=True,
                verbose_name="Награда за выполнение привычки",
            ),
        ),
    ]
